#!/usr/bin/env python3
"""Convert the MAME 'dkong' ROM set into a C header for GIRDER.

usage: convert_roms.py <romdir> [outdir]   (default outdir: ../main/roms)
"""
import sys, zlib
from pathlib import Path

MAIN  = [('c_5et_g.bin', 0x1000), ('c_5ct_g.bin', 0x1000),
         ('c_5bt_g.bin', 0x1000), ('c_5at_g.bin', 0x1000)]
SND   =  ('s_3i_b.bin', 0x800)     # 2 KB of program, mirrored to fill the 8035's 4 KB
SAMP  =  ('s_3j_b.bin', 0x800)     # the sample pages the 8035 reads through its BUS port
CHR   = [('v_5h_b.bin', 0x800), ('v_3pt.bin', 0x800)]
SPR   = [('l_4m_b.bin', 0x800), ('l_4n_b.bin', 0x800),
         ('l_4r_b.bin', 0x800), ('l_4s_b.bin', 0x800)]
PAL_LO = ('c-2k.bpr', 0x100)       # palette low 4 bits, inverted
PAL_HI = ('c-2j.bpr', 0x100)       # palette high 4 bits, inverted
COLCODE= ('v-5e.bpr', 0x100)       # character colour codes, per column

def load(romdir, name, size):
    p = romdir / name
    if not p.exists():
        sys.exit(f'{name}: not found in {romdir}')
    data = p.read_bytes()
    if len(data) != size:
        sys.exit(f'{name}: {len(data)} bytes, expected {size}')
    print(f'  {name}: {len(data)} bytes, crc32 {zlib.crc32(data) & 0xffffffff:08x}')
    return data

def cat(romdir, items):
    return b''.join(load(romdir, n, s) for n, s in items)

def c_array(name, data, dims):
    lines = [f'static const uint8_t {name}{dims} = {{']
    for i in range(0, len(data), 24):
        lines.append('    ' + ','.join(f'0x{b:02X}' for b in data[i:i+24]) + ',')
    lines.append('};')
    return '\n'.join(lines)

def main():
    romdir = Path(sys.argv[1] if len(sys.argv) > 1 else 'dkong')
    outdir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent / 'main' / 'roms'
    outdir.mkdir(parents=True, exist_ok=True)
    print(f'ROMs: {romdir}')
    snd = load(romdir, *SND)
    out = ['/* dkong_roms.h - AUTO-GENERATED by tools/convert_roms.py - DO NOT COMMIT */',
           '#ifndef DKONG_ROMS_H', '#define DKONG_ROMS_H', '#include <stdint.h>', '',
           '/* Z80 program */', c_array('dk_rom', cat(romdir, MAIN), '[0x4000]'), '',
           '/* 8035 program: the 2 KB ROM is mirrored to fill its 4 KB address space */',
           c_array('dk_snd', snd + snd, '[0x1000]'), '',
           '/* the sample pages the 8035 fetches through its BUS port */',
           c_array('dk_samp', load(romdir, *SAMP), '[0x800]'), '',
           c_array('dk_chr', cat(romdir, CHR), '[0x1000]'), '',
           c_array('dk_spr', cat(romdir, SPR), '[0x2000]'), '',
           c_array('dk_pal_lo', load(romdir, *PAL_LO), '[0x100]'), '',
           c_array('dk_pal_hi', load(romdir, *PAL_HI), '[0x100]'), '',
           c_array('dk_colcode', load(romdir, *COLCODE), '[0x100]'), '',
           '#endif']
    (outdir / 'dkong_roms.h').write_text('\n'.join(out))
    print(f'wrote {outdir / "dkong_roms.h"}')

if __name__ == '__main__':
    main()
